# FROM nginx:latest
FROM openresty/openresty:alpine
# COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
# ADD ./nginx.conf /etc/nginx/conf.d/default.conf
